services:
  five_web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: five_mascotas_web
    restart: unless-stopped
    ports:
      - "3004:80"
    volumes:
      - ./data:/app/data
    environment:
      TZ: America/Santiago
    security_opt:
      - no-new-privileges:true
    networks:
      - five_public

networks:
  five_public:
    name: five_mascotas_public
    driver: bridge
