export const defaultTickers = [
  {
    id: 'ticker-1',
    text: '¡10% dto. en tu primera compra web!',
    couponCode: 'PRIMERA10',
    couponText: 'Usa el código PRIMERA10',
    extraInfo: 'Despacho rápido a todo Santiago · Horario tienda Lun-Sáb 10:00 a 20:00',
    active: true,
    order: 1,
  },
  {
    id: 'ticker-2',
    text: 'Envío Gratis en compras sobre $29.990 en Región Metropolitana',
    extraInfo: 'Entregas en 24 a 48 hrs hábiles garantizadas',
    active: true,
    order: 2,
  },
  {
    id: 'ticker-3',
    text: 'Super Descuentos en Farmacia y Antiparasitarios de temporada',
    couponCode: 'SALUD20',
    couponText: 'Cupón: SALUD20',
    extraInfo: 'Hasta agotar stock promocional',
    active: true,
    order: 3,
  },
];

export const defaultBanners = [
  {
    id: 'banner-hero-home',
    tag: 'SOLO POR ESTE FIN DE SEMANA',
    title: '2x1 en Camas, Mantas y Ropa',
    subtitle: 'Para perros y gatos de todos los tamaños. ¡Combínalas como quieras!',
    disclaimer: '*Válido hasta agotar stock. Descuento aplicado automáticamente al carrito.',
    ctaText: 'Ver Promociones 2x1',
    ctaHref: '/ofertas',
    couponCode: 'FINDE2X1',
    expiresAt: '2026-10-31T23:59:59',
    badge: '2x1 WEEKEND',
    active: true,
    order: 1,
  },
  {
    id: 'banner-perros',
    tag: 'ESPECIAL CANINO',
    title: 'Nutrición Premium para tu Perro',
    subtitle: 'Alimentos secos, húmedos y snacks con hasta 25% de descuento.',
    ctaText: 'Explorar Alimentos para Perro',
    ctaHref: '/perros',
    couponCode: 'CANINO25',
    expiresAt: '2026-10-15T23:59:59',
    badge: 'HASTA 25% OFF',
    petTarget: 'Perros',
    active: true,
    order: 2,
  },
  {
    id: 'banner-gatos',
    tag: 'MUNDO FELINO',
    title: 'Todo para los Reyes de la Casa',
    subtitle: 'Arenas aglomerantes, rascadores y latitas gourmet seleccionadas.',
    ctaText: 'Ver Todo para Gatos',
    ctaHref: '/gatos',
    badge: 'SUPER PRECIOS',
    petTarget: 'Gatos',
    active: true,
    order: 3,
  },
  {
    id: 'banner-ofertas',
    tag: 'ZONA DE OPORTUNIDADES',
    title: 'Liquidaciones y SuperPrecios FIVE',
    subtitle: 'Encuentra las mejores marcas al precio más conveniente.',
    ctaText: 'Aprovechar Ofertas',
    ctaHref: '/ofertas',
    badge: 'LIQUIDACIÓN',
    active: true,
    order: 4,
  },
];

export const defaultHeroSlides = [
  {
    id: 'hero-1',
    badge: '🐾 SU MUNDO EMPIEZA CONTIGO',
    title: 'Ellos ponen el amor. Tú, lo mejor.',
    subtitle: 'Alimentos balanceados para quienes te reciben con alegría, te acompañan en silencio y hacen de tu casa un verdadero hogar.',
    ctaText: 'Explora la tienda',
    ctaHref: '/alimentos',
    image: '/demos/miga/dog.webp',
    imageAlt: 'Perro feliz disfrutando al aire libre',
    active: true,
    order: 1,
  },
  {
    id: 'hero-2',
    badge: '🐱 REYES DE LA CASA',
    title: 'Nutrición Gourmet y Confort Felino',
    subtitle: 'Alimentos húmedos seleccionados, rascadores resistentes y arenas aglomerantes para su máximo confort.',
    ctaText: 'Ver Todo para Gatos',
    ctaHref: '/gatos',
    image: '/five-mascotas/alimento-1.svg',
    imageAlt: 'Nutrición premium para gatos',
    active: true,
    order: 2,
  },
  {
    id: 'hero-3',
    badge: '💊 SALUD Y BIENESTAR',
    title: 'Farmacia Especializada y Prevención',
    subtitle: 'Antiparasitarios líderes, suplementos y cuidados clínicos para acompañar cada etapa de tu mascota.',
    ctaText: 'Cuidado y Farmacia',
    ctaHref: '/farmacia',
    image: '/five-mascotas/botiquin.svg',
    imageAlt: 'Botiquín y farmacia veterinaria',
    active: true,
    order: 3,
  },
];

export const defaultProducts = [
  { id: 'p-1', name: 'Alimento para perro adulto', pet: 'Perros', brand: 'Wellness Core', category: 'Alimentos', subcategory: 'Alimento seco', detail: 'Pollo y arroz · 15 kg', format: '15 kg', lifeStage: 'Adulto', price: 32990, oldPrice: 36990, badge: 'Liquidación', color: 'violet', image: '/five-mascotas/alimento-0.svg' },
  { id: 'p-2', name: 'Alimento para gato adulto', pet: 'Gatos', brand: 'Royal Canin', category: 'Alimentos', subcategory: 'Alimento seco', detail: 'Salmón · 7,5 kg', format: '7,5 kg', lifeStage: 'Adulto', price: 24990, oldPrice: 0, badge: 'SuperPrecios', color: 'green', image: '/five-mascotas/alimento-1.svg' },
  { id: 'p-3', name: 'Alimento para cachorros', pet: 'Perros', brand: 'Hill\'s Science Diet', category: 'Alimentos', subcategory: 'Alimento seco', detail: 'Pollo · 10 kg', format: '10 kg', lifeStage: 'Cachorro', price: 28990, oldPrice: 0, badge: '15% Dcto', color: 'peach', image: '/five-mascotas/alimento-2.svg' },
  { id: 'p-4', name: 'Alimento para gato esterilizado', pet: 'Gatos', brand: 'Pro Plan', category: 'Alimentos', subcategory: 'Alimento seco', detail: 'Pollo · 7,5 kg', format: '7,5 kg', lifeStage: 'Adulto', price: 26990, oldPrice: 29990, badge: '30% en 2da', color: 'lavender', image: '/five-mascotas/alimento-3.svg' },
  { id: 'p-5', name: 'Kit de primeros auxilios', pet: 'Perros Gatos', brand: 'FIVE Care', category: 'Farmacia', subcategory: 'Farmacia', detail: 'Estuche de cuidado · Clínico', format: 'Kit completo', lifeStage: 'Todas las edades', price: 15990, oldPrice: 0, badge: 'Salud', color: 'green', image: '/five-mascotas/botiquin.svg' },
  { id: 'p-6', name: 'Gasas de cuidado estériles', pet: 'Perros Gatos', brand: 'FIVE Care', category: 'Farmacia', subcategory: 'Farmacia', detail: 'Pack de 10 unidades', format: 'Pack 10 un', lifeStage: 'Todas las edades', price: 3990, oldPrice: 0, badge: '', color: 'lavender', image: '/five-mascotas/gasas.svg' },
  { id: 'p-7', name: 'Plato de cerámica pesado', pet: 'Perros Gatos', brand: 'Zee.Dog', category: 'Accesorios', subcategory: 'Platos y bebederos', detail: '650 ml · Oliva mate', format: '650 ml', lifeStage: 'Todas las edades', price: 9990, oldPrice: 11990, badge: 'Oferta', color: 'green', image: '/demos/miga/plato.svg' },
  { id: 'p-8', name: 'Pelota con textura TPR', pet: 'Perros', brand: 'Kong', category: 'Accesorios', subcategory: 'Juguetes', detail: 'Tamaño M · Naranja ultra resistente', format: 'Tamaño M', lifeStage: 'Todas las edades', price: 4990, oldPrice: 0, badge: '', color: 'peach', image: '/demos/miga/pelota.svg' },
  { id: 'p-9', name: 'Arena aglomerante natural', pet: 'Gatos', brand: 'OdourLock', category: 'Higiene', subcategory: 'Arenas aglomerantes', detail: 'Sin aroma · Control olor 40 días', format: '4 kg', lifeStage: 'Todas las edades', price: 11990, oldPrice: 0, badge: 'Top Ventas', color: 'lavender', image: '/demos/miga/arena.svg' },
  { id: 'p-10', name: 'Bocados suaves para premiar', pet: 'Perros', brand: 'Wanpy', category: 'Snacks', subcategory: 'Snack y premios', detail: 'Snack horneado sabor pato y calabaza', format: '100 g', lifeStage: 'Todas las edades', price: 3990, oldPrice: 4990, badge: 'Oferta', color: 'peach', image: '/demos/miga/snack.svg' },
];
